<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Timezone;

class TimezonesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Timezone::create(['name' => 'Pacific/Midway', 'description' => "(UTC-11:00) Midway Island"]);
        Timezone::create(['name' => 'Pacific/Samoa', 'description' => "(UTC-11:00) Samoa"]);
        Timezone::create(['name' => 'Pacific/Honolulu', 'description' => "(UTC-10:00) Hawaii"]);
        Timezone::create(['name' => 'US/Alaska', 'description' => "(UTC-09:00) Alaska"]);
        Timezone::create(['name' => 'America/Los_Angeles', 'description' => "(UTC-08:00) Pacific Time (US &amp; Canada)"]);
        Timezone::create(['name' => 'America/Tijuana', 'description' => "(UTC-08:00) Tijuana"]);
        Timezone::create(['name' => 'US/Arizona', 'description' => "(UTC-07:00) Arizona"]);
        Timezone::create(['name' => 'America/Chihuahua', 'description' => "(UTC-07:00) Chihuahua"]);
        Timezone::create(['name' => 'America/Chihuahua', 'description' => "(UTC-07:00) La Paz"]);
        Timezone::create(['name' => 'America/Mazatlan', 'description' => "(UTC-07:00) Mazatlan"]);
        Timezone::create(['name' => 'US/Mountain', 'description' => "(UTC-07:00) Mountain Time (US &amp; Canada)"]);
        Timezone::create(['name' => 'America/Managua', 'description' => "(UTC-06:00) Central America"]);
        Timezone::create(['name' => 'US/Central', 'description' => "(UTC-06:00) Central Time (US &amp; Canada)"]);
        Timezone::create(['name' => 'America/Mexico_City', 'description' => "(UTC-06:00) Guadalajara"]);
        Timezone::create(['name' => 'America/Mexico_City', 'description' => "(UTC-06:00) Mexico City"]);
        Timezone::create(['name' => 'America/Monterrey', 'description' => "(UTC-06:00) Monterrey"]);
        Timezone::create(['name' => 'Canada/Saskatchewan', 'description' => "(UTC-06:00) Saskatchewan"]);
        Timezone::create(['name' => 'America/Bogota', 'description' => "(UTC-05:00) Bogota"]);
        Timezone::create(['name' => 'US/Eastern', 'description' => "(UTC-05:00) Eastern Time (US &amp; Canada)"]);
        Timezone::create(['name' => 'US/East-Indiana', 'description' => "(UTC-05:00) Indiana (East)"]);
        Timezone::create(['name' => 'America/Lima', 'description' => "(UTC-05:00) Lima"]);
        Timezone::create(['name' => 'America/Bogota', 'description' => "(UTC-05:00) Quito"]);
        Timezone::create(['name' => 'Canada/Atlantic', 'description' => "(UTC-04:00) Atlantic Time (Canada)"]);
        Timezone::create(['name' => 'America/Caracas', 'description' => "(UTC-04:30) Caracas"]);
        Timezone::create(['name' => 'America/La_Paz', 'description' => "(UTC-04:00) La Paz"]);
        Timezone::create(['name' => 'America/Santiago', 'description' => "(UTC-04:00) Santiago"]);
        Timezone::create(['name' => 'Canada/Newfoundland', 'description' => "(UTC-03:30) Newfoundland"]);
        Timezone::create(['name' => 'America/Sao_Paulo', 'description' => "(UTC-03:00) Brasilia"]);
        Timezone::create(['name' => 'America/Argentina/Buenos_Aires', 'description' => "(UTC-03:00) Buenos Aires"]);
        Timezone::create(['name' => 'America/Argentina/Buenos_Aires', 'description' => "(UTC-03:00) Georgetown"]);
        Timezone::create(['name' => 'America/Godthab', 'description' => "(UTC-03:00) Greenland"]);
        Timezone::create(['name' => 'America/Noronha', 'description' => "(UTC-02:00) Mid-Atlantic"]);
        Timezone::create(['name' => 'Atlantic/Azores', 'description' => "(UTC-01:00) Azores"]);
        Timezone::create(['name' => 'Atlantic/Cape_Verde', 'description' => "(UTC-01:00) Cape Verde Is."]);
        Timezone::create(['name' => 'Africa/Casablanca', 'description' => "(UTC+00:00) Casablanca"]);
        Timezone::create(['name' => 'Europe/London', 'description' => "(UTC+00:00) Edinburgh"]);
        Timezone::create(['name' => 'Etc/Greenwich', 'description' => "(UTC+00:00) Greenwich Mean Time : Dublin"]);
        Timezone::create(['name' => 'Europe/Lisbon', 'description' => "(UTC+00:00) Lisbon"]);
        Timezone::create(['name' => 'Europe/London', 'description' => "(UTC+00:00) London"]);
        Timezone::create(['name' => 'Africa/Monrovia', 'description' => "(UTC+00:00) Monrovia"]);
        Timezone::create(['name' => 'UTC', 'description' => "(UTC+00:00) UTC"]);
        Timezone::create(['name' => 'Europe/Amsterdam', 'description' => "(UTC+01:00) Amsterdam"]);
        Timezone::create(['name' => 'Europe/Belgrade', 'description' => "(UTC+01:00) Belgrade"]);
        Timezone::create(['name' => 'Europe/Berlin', 'description' => "(UTC+01:00) Berlin"]);
        Timezone::create(['name' => 'Europe/Berlin', 'description' => "(UTC+01:00) Bern"]);
        Timezone::create(['name' => 'Europe/Bratislava', 'description' => "(UTC+01:00) Bratislava"]);
        Timezone::create(['name' => 'Europe/Brussels', 'description' => "(UTC+01:00) Brussels"]);
        Timezone::create(['name' => 'Europe/Budapest', 'description' => "(UTC+01:00) Budapest"]);
        Timezone::create(['name' => 'Europe/Copenhagen', 'description' => "(UTC+01:00) Copenhagen"]);
        Timezone::create(['name' => 'Europe/Ljubljana', 'description' => "(UTC+01:00) Ljubljana"]);
        Timezone::create(['name' => 'Europe/Madrid', 'description' => "(UTC+01:00) Madrid"]);
        Timezone::create(['name' => 'Europe/Paris', 'description' => "(UTC+01:00) Paris"]);
        Timezone::create(['name' => 'Europe/Prague', 'description' => "(UTC+01:00) Prague"]);
        Timezone::create(['name' => 'Europe/Rome', 'description' => "(UTC+01:00) Rome"]);
        Timezone::create(['name' => 'Europe/Sarajevo', 'description' => "(UTC+01:00) Sarajevo"]);
        Timezone::create(['name' => 'Europe/Skopje', 'description' => "(UTC+01:00) Skopje"]);
        Timezone::create(['name' => 'Europe/Stockholm', 'description' => "(UTC+01:00) Stockholm"]);
        Timezone::create(['name' => 'Europe/Vienna', 'description' => "(UTC+01:00) Vienna"]);
        Timezone::create(['name' => 'Europe/Warsaw', 'description' => "(UTC+01:00) Warsaw"]);
        Timezone::create(['name' => 'Africa/Lagos', 'description' => "(UTC+01:00) West Central Africa"]);
        Timezone::create(['name' => 'Europe/Zagreb', 'description' => "(UTC+01:00) Zagreb"]);
        Timezone::create(['name' => 'Europe/Athens', 'description' => "(UTC+02:00) Athens"]);
        Timezone::create(['name' => 'Europe/Bucharest', 'description' => "(UTC+02:00) Bucharest"]);
        Timezone::create(['name' => 'Africa/Cairo', 'description' => "(UTC+02:00) Cairo"]);
        Timezone::create(['name' => 'Africa/Harare', 'description' => "(UTC+02:00) Harare"]);
        Timezone::create(['name' => 'Europe/Helsinki', 'description' => "(UTC+02:00) Helsinki"]);
        Timezone::create(['name' => 'Europe/Istanbul', 'description' => "(UTC+02:00) Istanbul"]);
        Timezone::create(['name' => 'Asia/Jerusalem', 'description' => "(UTC+02:00) Jerusalem"]);
        Timezone::create(['name' => 'Europe/Helsinki', 'description' => "(UTC+02:00) Kyiv"]);
        Timezone::create(['name' => 'Africa/Johannesburg', 'description' => "(UTC+02:00) Pretoria"]);
        Timezone::create(['name' => 'Europe/Riga', 'description' => "(UTC+02:00) Riga"]);
        Timezone::create(['name' => 'Europe/Sofia', 'description' => "(UTC+02:00) Sofia"]);
        Timezone::create(['name' => 'Europe/Tallinn', 'description' => "(UTC+02:00) Tallinn"]);
        Timezone::create(['name' => 'Europe/Vilnius', 'description' => "(UTC+02:00) Vilnius"]);
        Timezone::create(['name' => 'Asia/Baghdad', 'description' => "(UTC+03:00) Baghdad"]);
        Timezone::create(['name' => 'Asia/Kuwait', 'description' => "(UTC+03:00) Kuwait"]);
        Timezone::create(['name' => 'Europe/Minsk', 'description' => "(UTC+03:00) Minsk"]);
        Timezone::create(['name' => 'Africa/Nairobi', 'description' => "(UTC+03:00) Nairobi"]);
        Timezone::create(['name' => 'Asia/Riyadh', 'description' => "(UTC+03:00) Riyadh"]);
        Timezone::create(['name' => 'Europe/Volgograd', 'description' => "(UTC+03:00) Volgograd"]);
        Timezone::create(['name' => 'Asia/Tehran', 'description' => "(UTC+03:30) Tehran"]);
        Timezone::create(['name' => 'Asia/Muscat', 'description' => "(UTC+04:00) Abu Dhabi"]);
        Timezone::create(['name' => 'Asia/Baku', 'description' => "(UTC+04:00) Baku"]);
        Timezone::create(['name' => 'Europe/Moscow', 'description' => "(UTC+04:00) Moscow"]);
        Timezone::create(['name' => 'Asia/Muscat', 'description' => "(UTC+04:00) Muscat"]);
        Timezone::create(['name' => 'Europe/Moscow', 'description' => "(UTC+04:00) St. Petersburg"]);
        Timezone::create(['name' => 'Asia/Tbilisi', 'description' => "(UTC+04:00) Tbilisi"]);
        Timezone::create(['name' => 'Asia/Yerevan', 'description' => "(UTC+04:00) Yerevan"]);
        Timezone::create(['name' => 'Asia/Kabul', 'description' => "(UTC+04:30) Kabul"]);
        Timezone::create(['name' => 'Asia/Karachi', 'description' => "(UTC+05:00) Islamabad"]);
        Timezone::create(['name' => 'Asia/Karachi', 'description' => "(UTC+05:00) Karachi"]);
        Timezone::create(['name' => 'Asia/Tashkent', 'description' => "(UTC+05:00) Tashkent"]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) Chennai"]);
        Timezone::create(['name' => 'Asia/Kolkata', 'description' => "(UTC+05:30) Kolkata"]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) Mumbai"]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) New Delhi"]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) Sri Jayawardenepura"]);
        Timezone::create(['name' => 'Asia/Katmandu', 'description' => "(UTC+05:45) Kathmandu"]);
        Timezone::create(['name' => 'Asia/Almaty', 'description' => "(UTC+06:00) Almaty"]);
        Timezone::create(['name' => 'Asia/Dhaka', 'description' => "(UTC+06:00) Astana"]);
        Timezone::create(['name' => 'Asia/Dhaka', 'description' => "(UTC+06:00) Dhaka"]);
        Timezone::create(['name' => 'Asia/Yekaterinburg', 'description' => "(UTC+06:00) Ekaterinburg"]);
        Timezone::create(['name' => 'Asia/Rangoon', 'description' => "(UTC+06:30) Rangoon"]);
        Timezone::create(['name' => 'Asia/Bangkok', 'description' => "(UTC+07:00) Bangkok"]);
        Timezone::create(['name' => 'Asia/Bangkok', 'description' => "(UTC+07:00) Hanoi"]);
        Timezone::create(['name' => 'Asia/Jakarta', 'description' => "(UTC+07:00) Jakarta"]);
        Timezone::create(['name' => 'Asia/Novosibirsk', 'description' => "(UTC+07:00) Novosibirsk"]);
        Timezone::create(['name' => 'Asia/Hong_Kong', 'description' => "(UTC+08:00) Beijing"]);
        Timezone::create(['name' => 'Asia/Chongqing', 'description' => "(UTC+08:00) Chongqing"]);
        Timezone::create(['name' => 'Asia/Hong_Kong', 'description' => "(UTC+08:00) Hong Kong"]);
        Timezone::create(['name' => 'Asia/Krasnoyarsk', 'description' => "(UTC+08:00) Krasnoyarsk"]);
        Timezone::create(['name' => 'Asia/Kuala_Lumpur', 'description' => "(UTC+08:00) Kuala Lumpur"]);
        Timezone::create(['name' => 'Australia/Perth', 'description' => "(UTC+08:00) Perth"]);
        Timezone::create(['name' => 'Asia/Singapore', 'description' => "(UTC+08:00) Singapore"]);
        Timezone::create(['name' => 'Asia/Taipei', 'description' => "(UTC+08:00) Taipei"]);
        Timezone::create(['name' => 'Asia/Ulan_Bator', 'description' => "(UTC+08:00) Ulaan Bataar"]);
        Timezone::create(['name' => 'Asia/Urumqi', 'description' => "(UTC+08:00) Urumqi"]);
        Timezone::create(['name' => 'Asia/Irkutsk', 'description' => "(UTC+09:00) Irkutsk"]);
        Timezone::create(['name' => 'Asia/Tokyo', 'description' => "(UTC+09:00) Osaka"]);
        Timezone::create(['name' => 'Asia/Tokyo', 'description' => "(UTC+09:00) Sapporo"]);
        Timezone::create(['name' => 'Asia/Seoul', 'description' => "(UTC+09:00) Seoul"]);
        Timezone::create(['name' => 'Asia/Tokyo', 'description' => "(UTC+09:00) Tokyo"]);
        Timezone::create(['name' => 'Australia/Adelaide', 'description' => "(UTC+09:30) Adelaide"]);
        Timezone::create(['name' => 'Australia/Darwin', 'description' => "(UTC+09:30) Darwin"]);
        Timezone::create(['name' => 'Australia/Brisbane', 'description' => "(UTC+10:00) Brisbane"]);
        Timezone::create(['name' => 'Australia/Canberra', 'description' => "(UTC+10:00) Canberra"]);
        Timezone::create(['name' => 'Pacific/Guam', 'description' => "(UTC+10:00) Guam"]);
        Timezone::create(['name' => 'Australia/Hobart', 'description' => "(UTC+10:00) Hobart"]);
        Timezone::create(['name' => 'Australia/Melbourne', 'description' => "(UTC+10:00) Melbourne"]);
        Timezone::create(['name' => 'Pacific/Port_Moresby', 'description' => "(UTC+10:00) Port Moresby"]);
        Timezone::create(['name' => 'Australia/Sydney', 'description' => "(UTC+10:00) Sydney"]);
        Timezone::create(['name' => 'Asia/Yakutsk', 'description' => "(UTC+10:00) Yakutsk"]);
        Timezone::create(['name' => 'Asia/Vladivostok', 'description' => "(UTC+11:00) Vladivostok"]);
        Timezone::create(['name' => 'Pacific/Auckland', 'description' => "(UTC+12:00) Auckland"]);
        Timezone::create(['name' => 'Pacific/Fiji', 'description' => "(UTC+12:00) Fiji"]);
        Timezone::create(['name' => 'Pacific/Kwajalein', 'description' => "(UTC+12:00) International Date Line West"]);
        Timezone::create(['name' => 'Asia/Kamchatka', 'description' => "(UTC+12:00) Kamchatka"]);
        Timezone::create(['name' => 'Asia/Magadan', 'description' => "(UTC+12:00) Magadan"]);
        Timezone::create(['name' => 'Pacific/Fiji', 'description' => "(UTC+12:00) Marshall Is."]);
        Timezone::create(['name' => 'Asia/Magadan', 'description' => "(UTC+12:00) New Caledonia"]);
        Timezone::create(['name' => 'Asia/Magadan', 'description' => "(UTC+12:00) Solomon Is."]);
        Timezone::create(['name' => 'Pacific/Auckland', 'description' => "(UTC+12:00) Wellington"]);
        Timezone::create(['name' => 'Pacific/Tongatapu', 'description' => "(UTC+13:00) Nuku'alofa"]);
    }
}
