<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Timezone;

class TimezonesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Timezone::create(['name' => 'Pacific/Midway', 'description' => "(UTC-11:00) Midway Island", "offset_hours" => -11, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Samoa', 'description' => "(UTC-11:00) Samoa", "offset_hours" => -11, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Honolulu', 'description' => "(UTC-10:00) Hawaii", "offset_hours" => -10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'US/Alaska', 'description' => "(UTC-09:00) Alaska", "offset_hours" => -9, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Los_Angeles', 'description' => "(UTC-08:00) Pacific Time (US &amp; Canada)", "offset_hours" => -8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Tijuana', 'description' => "(UTC-08:00) Tijuana", "offset_hours" => -8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'US/Arizona', 'description' => "(UTC-07:00) Arizona", "offset_hours" => -7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Chihuahua', 'description' => "(UTC-07:00) Chihuahua", "offset_hours" => -7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Chihuahua', 'description' => "(UTC-07:00) La Paz", "offset_hours" => -7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Mazatlan', 'description' => "(UTC-07:00) Mazatlan", "offset_hours" => -7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'US/Mountain', 'description' => "(UTC-07:00) Mountain Time (US &amp; Canada)", "offset_hours" => -7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Managua', 'description' => "(UTC-06:00) Central America", "offset_hours" => -6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'US/Central', 'description' => "(UTC-06:00) Central Time (US &amp; Canada)", "offset_hours" => -6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Mexico_City', 'description' => "(UTC-06:00) Guadalajara", "offset_hours" => -6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Mexico_City', 'description' => "(UTC-06:00) Mexico City", "offset_hours" => -6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Monterrey', 'description' => "(UTC-06:00) Monterrey", "offset_hours" => -6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Canada/Saskatchewan', 'description' => "(UTC-06:00) Saskatchewan", "offset_hours" => -6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Bogota', 'description' => "(UTC-05:00) Bogota", "offset_hours" => -5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'US/Eastern', 'description' => "(UTC-05:00) Eastern Time (US &amp; Canada)", "offset_hours" => -5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'US/East-Indiana', 'description' => "(UTC-05:00) Indiana (East)", "offset_hours" => -5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Lima', 'description' => "(UTC-05:00) Lima", "offset_hours" => -5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Bogota', 'description' => "(UTC-05:00) Quito", "offset_hours" => -5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Canada/Atlantic', 'description' => "(UTC-04:00) Atlantic Time (Canada)", "offset_hours" => -4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Caracas', 'description' => "(UTC-04:30) Caracas", "offset_hours" => -4, "offset_minutes" => 30]);
        Timezone::create(['name' => 'America/La_Paz', 'description' => "(UTC-04:00) La Paz", "offset_hours" => -4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Santiago', 'description' => "(UTC-04:00) Santiago", "offset_hours" => -4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Canada/Newfoundland', 'description' => "(UTC-03:30) Newfoundland", "offset_hours" => -3, "offset_minutes" => 30]);
        Timezone::create(['name' => 'America/Sao_Paulo', 'description' => "(UTC-03:00) Brasilia", "offset_hours" => -3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Argentina/Buenos_Aires', 'description' => "(UTC-03:00) Buenos Aires", "offset_hours" => -3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Argentina/Buenos_Aires', 'description' => "(UTC-03:00) Georgetown", "offset_hours" => -3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Godthab', 'description' => "(UTC-03:00) Greenland", "offset_hours" => -3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'America/Noronha', 'description' => "(UTC-02:00) Mid-Atlantic", "offset_hours" => -2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Atlantic/Azores', 'description' => "(UTC-01:00) Azores", "offset_hours" => -1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Atlantic/Cape_Verde', 'description' => "(UTC-01:00) Cape Verde Is.", "offset_hours" => -1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Africa/Casablanca', 'description' => "(UTC+00:00) Casablanca", "offset_hours" => 0, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/London', 'description' => "(UTC+00:00) Edinburgh", "offset_hours" => 0, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Etc/Greenwich', 'description' => "(UTC+00:00) Greenwich Mean Time : Dublin", "offset_hours" => 0, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Lisbon', 'description' => "(UTC+00:00) Lisbon", "offset_hours" => 0, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/London', 'description' => "(UTC+00:00) London", "offset_hours" => 0, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Africa/Monrovia', 'description' => "(UTC+00:00) Monrovia", "offset_hours" => 0, "offset_minutes" => 0]);
        Timezone::create(['name' => 'UTC', 'description' => "(UTC+00:00) UTC", "offset_hours" => 0, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Amsterdam', 'description' => "(UTC+01:00) Amsterdam", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Belgrade', 'description' => "(UTC+01:00) Belgrade", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Berlin', 'description' => "(UTC+01:00) Berlin", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Berlin', 'description' => "(UTC+01:00) Bern", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Bratislava', 'description' => "(UTC+01:00) Bratislava", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Brussels', 'description' => "(UTC+01:00) Brussels", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Budapest', 'description' => "(UTC+01:00) Budapest", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Copenhagen', 'description' => "(UTC+01:00) Copenhagen", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Ljubljana', 'description' => "(UTC+01:00) Ljubljana", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Madrid', 'description' => "(UTC+01:00) Madrid", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Paris', 'description' => "(UTC+01:00) Paris", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Prague', 'description' => "(UTC+01:00) Prague", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Rome', 'description' => "(UTC+01:00) Rome", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Sarajevo', 'description' => "(UTC+01:00) Sarajevo", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Skopje', 'description' => "(UTC+01:00) Skopje", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Stockholm', 'description' => "(UTC+01:00) Stockholm", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Vienna', 'description' => "(UTC+01:00) Vienna", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Warsaw', 'description' => "(UTC+01:00) Warsaw", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Africa/Lagos', 'description' => "(UTC+01:00) West Central Africa", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Zagreb', 'description' => "(UTC+01:00) Zagreb", "offset_hours" => 1, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Athens', 'description' => "(UTC+02:00) Athens", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Bucharest', 'description' => "(UTC+02:00) Bucharest", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Africa/Cairo', 'description' => "(UTC+02:00) Cairo", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Africa/Harare', 'description' => "(UTC+02:00) Harare", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Helsinki', 'description' => "(UTC+02:00) Helsinki", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Istanbul', 'description' => "(UTC+02:00) Istanbul", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Jerusalem', 'description' => "(UTC+02:00) Jerusalem", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Helsinki', 'description' => "(UTC+02:00) Kyiv", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Africa/Johannesburg', 'description' => "(UTC+02:00) Pretoria", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Riga', 'description' => "(UTC+02:00) Riga", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Sofia', 'description' => "(UTC+02:00) Sofia", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Tallinn', 'description' => "(UTC+02:00) Tallinn", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Vilnius', 'description' => "(UTC+02:00) Vilnius", "offset_hours" => 2, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Baghdad', 'description' => "(UTC+03:00) Baghdad", "offset_hours" => 3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Kuwait', 'description' => "(UTC+03:00) Kuwait", "offset_hours" => 3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Minsk', 'description' => "(UTC+03:00) Minsk", "offset_hours" => 3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Africa/Nairobi', 'description' => "(UTC+03:00) Nairobi", "offset_hours" => 3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Riyadh', 'description' => "(UTC+03:00) Riyadh", "offset_hours" => 3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Volgograd', 'description' => "(UTC+03:00) Volgograd", "offset_hours" => 3, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Tehran', 'description' => "(UTC+03:30) Tehran", "offset_hours" => 3, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Muscat', 'description' => "(UTC+04:00) Abu Dhabi", "offset_hours" => 4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Baku', 'description' => "(UTC+04:00) Baku", "offset_hours" => 4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Moscow', 'description' => "(UTC+04:00) Moscow", "offset_hours" => 4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Muscat', 'description' => "(UTC+04:00) Muscat", "offset_hours" => 4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Europe/Moscow', 'description' => "(UTC+04:00) St. Petersburg", "offset_hours" => 4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Tbilisi', 'description' => "(UTC+04:00) Tbilisi", "offset_hours" => 4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Yerevan', 'description' => "(UTC+04:00) Yerevan", "offset_hours" => 4, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Kabul', 'description' => "(UTC+04:30) Kabul", "offset_hours" => 4, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Karachi', 'description' => "(UTC+05:00) Islamabad", "offset_hours" => 5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Karachi', 'description' => "(UTC+05:00) Karachi", "offset_hours" => 5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Tashkent', 'description' => "(UTC+05:00) Tashkent", "offset_hours" => 5, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) Chennai", "offset_hours" => 5, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Kolkata', 'description' => "(UTC+05:30) Kolkata", "offset_hours" => 5, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) Mumbai", "offset_hours" => 5, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) New Delhi", "offset_hours" => 5, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Calcutta', 'description' => "(UTC+05:30) Sri Jayawardenepura", "offset_hours" => 5, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Katmandu', 'description' => "(UTC+05:45) Kathmandu", "offset_hours" => 5, "offset_minutes" => 45]);
        Timezone::create(['name' => 'Asia/Almaty', 'description' => "(UTC+06:00) Almaty", "offset_hours" => 6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Dhaka', 'description' => "(UTC+06:00) Astana", "offset_hours" => 6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Dhaka', 'description' => "(UTC+06:00) Dhaka", "offset_hours" => 6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Yekaterinburg', 'description' => "(UTC+06:00) Ekaterinburg", "offset_hours" => 6, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Rangoon', 'description' => "(UTC+06:30) Rangoon", "offset_hours" => 6, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Asia/Bangkok', 'description' => "(UTC+07:00) Bangkok", "offset_hours" => 7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Bangkok', 'description' => "(UTC+07:00) Hanoi", "offset_hours" => 7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Jakarta', 'description' => "(UTC+07:00) Jakarta", "offset_hours" => 7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Novosibirsk', 'description' => "(UTC+07:00) Novosibirsk", "offset_hours" => 7, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Hong_Kong', 'description' => "(UTC+08:00) Beijing", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Chongqing', 'description' => "(UTC+08:00) Chongqing", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Hong_Kong', 'description' => "(UTC+08:00) Hong Kong", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Krasnoyarsk', 'description' => "(UTC+08:00) Krasnoyarsk", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Kuala_Lumpur', 'description' => "(UTC+08:00) Kuala Lumpur", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Australia/Perth', 'description' => "(UTC+08:00) Perth", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Singapore', 'description' => "(UTC+08:00) Singapore", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Taipei', 'description' => "(UTC+08:00) Taipei", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Ulan_Bator', 'description' => "(UTC+08:00) Ulaan Bataar", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Urumqi', 'description' => "(UTC+08:00) Urumqi", "offset_hours" => 8, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Irkutsk', 'description' => "(UTC+09:00) Irkutsk", "offset_hours" => 9, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Tokyo', 'description' => "(UTC+09:00) Osaka", "offset_hours" => 9, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Tokyo', 'description' => "(UTC+09:00) Sapporo", "offset_hours" => 9, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Seoul', 'description' => "(UTC+09:00) Seoul", "offset_hours" => 9, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Tokyo', 'description' => "(UTC+09:00) Tokyo", "offset_hours" => 9, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Australia/Adelaide', 'description' => "(UTC+09:30) Adelaide", "offset_hours" => 9, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Australia/Darwin', 'description' => "(UTC+09:30) Darwin", "offset_hours" => 9, "offset_minutes" => 30]);
        Timezone::create(['name' => 'Australia/Brisbane', 'description' => "(UTC+10:00) Brisbane", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Australia/Canberra', 'description' => "(UTC+10:00) Canberra", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Guam', 'description' => "(UTC+10:00) Guam", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Australia/Hobart', 'description' => "(UTC+10:00) Hobart", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Australia/Melbourne', 'description' => "(UTC+10:00) Melbourne", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Port_Moresby', 'description' => "(UTC+10:00) Port Moresby", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Australia/Sydney', 'description' => "(UTC+10:00) Sydney", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Yakutsk', 'description' => "(UTC+10:00) Yakutsk", "offset_hours" => 10, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Vladivostok', 'description' => "(UTC+11:00) Vladivostok", "offset_hours" => 11, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Auckland', 'description' => "(UTC+12:00) Auckland", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Fiji', 'description' => "(UTC+12:00) Fiji", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Kwajalein', 'description' => "(UTC+12:00) International Date Line West", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Kamchatka', 'description' => "(UTC+12:00) Kamchatka", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Magadan', 'description' => "(UTC+12:00) Magadan", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Fiji', 'description' => "(UTC+12:00) Marshall Is.", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Magadan', 'description' => "(UTC+12:00) New Caledonia", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Asia/Magadan', 'description' => "(UTC+12:00) Solomon Is.", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Auckland', 'description' => "(UTC+12:00) Wellington", "offset_hours" => 12, "offset_minutes" => 0]);
        Timezone::create(['name' => 'Pacific/Tongatapu', 'description' => "(UTC+13:00) Nuku'alofa", "offset_hours" => 13, "offset_minutes" => 0]);
    }
}
